# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dangnhap.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLineEdit 
from PyQt5.QtGui import QIcon
import os
import sys
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'SaveClass')))
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'main')))
from classtk import taikhoan
from main import Ui_MainWindowm


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(728, 441)
        MainWindow.setWindowIcon(QIcon("main/PetHaven.png"))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 371, 441))
        self.groupBox.setStyleSheet("border-image: url(:/bgr/pethaven2.png);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(380, 0, 351, 441))
        self.groupBox_2.setStyleSheet("")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(90, 80, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tb_tk = QtWidgets.QLineEdit(self.groupBox_2)
        self.tb_tk.setGeometry(QtCore.QRect(160, 130, 161, 31))
        self.tb_tk.setObjectName("tb_tk")
        self.tb_mk = QtWidgets.QLineEdit(self.groupBox_2)
        self.tb_mk.setGeometry(QtCore.QRect(160, 180, 161, 31))
        self.tb_mk.setObjectName("tb_mk")
        self.btn_dn = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_dn.setGeometry(QtCore.QRect(50, 280, 121, 41))
        self.btn_dn.setObjectName("btn_dn")
        self.btn_dmk = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_dmk.setGeometry(QtCore.QRect(190, 280, 121, 41))
        self.btn_dmk.setObjectName("btn_dmk")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit.setGeometry(QtCore.QRect(160, 230, 161, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.btn_huy = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_huy.setGeometry(QtCore.QRect(120, 330, 121, 41))
        self.btn_huy.setObjectName("btn_huy")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(11, 131, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 230, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(11, 183, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionQL_thu_cung = QtWidgets.QAction(MainWindow)
        self.actionQL_thu_cung.setObjectName("actionQL_thu_cung")
        self.actionQL_nhan_vien = QtWidgets.QAction(MainWindow)
        self.actionQL_nhan_vien.setObjectName("actionQL_nhan_vien")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.lineEdit.setEchoMode(QLineEdit.Password)
        self.tb_mk.setEchoMode(QLineEdit.Password)
        self.label_4.setHidden(True)
        self.lineEdit.setHidden(True)
        self.btn_huy.setHidden(True)
        self.btn_huy.clicked.connect(self.btnhuy)
        self.btn_dmk.clicked.connect(self.btndmk)
        self.btn_dn.clicked.connect(self.btndn)


    def btndn(self):
        tk = self.tb_tk.text()
        mk = self.tb_mk.text()
        tktk = taikhoan
        data = tktk.gettk(tk)
        if(len(data) == 0):
            halo=QtWidgets.QMessageBox()
            halo.setInformativeText(f'Tài khoản không chính xác')
            halo.exec()
        elif(str(data[0][1]) != mk):
            halo=QtWidgets.QMessageBox()
            halo.setInformativeText(f'Mật khẩu không chính xác')
            halo.exec()
        else:
            self.windowm = QtWidgets.QMainWindow()
            self.main = Ui_MainWindowm()
            self.main.setupUi(self.windowm,str(data[0][2]))
            self.windowm.show()
            MainWindow.hide()
        

    def btndmk(self):
        if(self.btn_dmk.text()=="ĐỔI MẬT KHẨU"):
            self.label_4.setHidden(False)
            self.lineEdit.setHidden(False)
            self.btn_huy.setHidden(False)
            self.btn_dmk.setText("XÁC NHẬN")
        else:
            tk = self.tb_tk.text()
            mk = self.tb_mk.text()
            tktk = taikhoan
            data = tktk.gettk(tk)
            if(len(data) == 0):
                halo=QtWidgets.QMessageBox()
                halo.setInformativeText(f'Tài khoản không chính xác')
                halo.exec()
            elif(str(data[0][1]) != mk):
                halo=QtWidgets.QMessageBox()
                halo.setInformativeText(f'Mật khẩu không chính xác')
                halo.exec()
            else:
                mkm = self.lineEdit.text()           
                tc = taikhoan(tk, mkm, "")
                tc.dmk()
                self.tb_mk.setText(mkm)
                self.btnhuy()
        
    def btnhuy(self):
        self.label_4.setHidden(True)
        self.lineEdit.setHidden(True)
        self.btn_huy.setHidden(True)
        self.btn_dmk.setText("ĐỔI MẬT KHẨU")
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ĐĂNG NHẬP"))
        self.label.setText(_translate("MainWindow", "ĐĂNG NHẬP"))
        self.btn_dn.setText(_translate("MainWindow", "ĐĂNG NHẬP"))
        self.btn_dmk.setText(_translate("MainWindow", "ĐỔI MẬT KHẨU"))
        self.btn_huy.setText(_translate("MainWindow", "Hủy"))
        self.label_2.setText(_translate("MainWindow", "Tài khoản:"))
        self.label_4.setText(_translate("MainWindow", "Mật khẩu mới:"))
        self.label_3.setText(_translate("MainWindow", "Mật khẩu :"))
        self.actionQL_thu_cung.setText(_translate("MainWindow", "QL thu cung"))
        self.actionQL_nhan_vien.setText(_translate("MainWindow", "QL nhan vien"))
import bgr


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
