# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QLDV.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem 
import os
import sys
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'SaveClass')))
from classdv import dichvu

class Ui_MainWindowdv(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1074, 653)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 121, 111))
        self.pushButton.setStyleSheet("border-image: url(:/newPrefix/Pet Haven.png);")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(760, 220, 131, 121))
        self.pushButton_2.setStyleSheet("border-image: url(:/newPrefix/self-service.png);")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(410, 0, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(200, 50, 611, 16))
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(130, 80, 781, 131))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 40, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 80, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(390, 40, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.tb_t = QtWidgets.QLineEdit(self.groupBox)
        self.tb_t.setGeometry(QtCore.QRect(520, 40, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tb_t.setFont(font)
        self.tb_t.setObjectName("tb_t")
        self.tb_m = QtWidgets.QLineEdit(self.groupBox)
        self.tb_m.setGeometry(QtCore.QRect(170, 40, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tb_m.setFont(font)
        self.tb_m.setObjectName("tb_m")
        self.cb_l = QtWidgets.QComboBox(self.groupBox)
        self.cb_l.setGeometry(QtCore.QRect(170, 80, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_l.setFont(font)
        self.cb_l.setObjectName("cb_l")
        self.cb_l.addItem("")
        self.cb_l.addItem("")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(390, 220, 370, 121))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(10, 50, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_3.setGeometry(QtCore.QRect(130, 30, 200, 31))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_4.setGeometry(QtCore.QRect(130, 70, 250, 31))
        self.checkBox_4.setObjectName("checkBox_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 220, 350, 121))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox.setGeometry(QtCore.QRect(130, 30, 200, 31))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_2.setGeometry(QtCore.QRect(130, 70, 250, 31))
        self.checkBox_2.setObjectName("checkBox_2")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 350, 1031, 241))
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        header = self.tableWidget.horizontalHeader()
        for i in range(self.tableWidget.columnCount()):
            header.setSectionResizeMode(i, QtWidgets.QHeaderView.Stretch)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.bt_t = QtWidgets.QPushButton(self.centralwidget)
        self.bt_t.setGeometry(QtCore.QRect(940, 100, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.bt_t.setFont(font)
        self.bt_t.setObjectName("bt_t")
        self.bt_t_2 = QtWidgets.QPushButton(self.centralwidget)
        self.bt_t_2.setGeometry(QtCore.QRect(940, 180, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.bt_t_2.setFont(font)
        self.bt_t_2.setObjectName("bt_t_2")
        self.bt_x = QtWidgets.QPushButton(self.centralwidget)
        self.bt_x.setGeometry(QtCore.QRect(940, 250, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.bt_x.setFont(font)
        self.bt_x.setObjectName("bt_x")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1074, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.hienthi()
        self.bt_t.clicked.connect(lambda:self.them())
        self.bt_t_2.clicked.connect(lambda:self.sua())
        self.bt_x.clicked.connect(lambda:self.xoa())
        self.tableWidget.cellClicked.connect(lambda:self.cellclick())

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Quản Lý Dịch Vụ "))
        self.groupBox.setTitle(_translate("MainWindow", "Thông tin khách hàng"))
        self.label_3.setText(_translate("MainWindow", "Tên khách hàng"))
        self.label_4.setText(_translate("MainWindow", "Loại thú cưng:"))
        self.label_6.setText(_translate("MainWindow", "Số điện thoại"))
        self.cb_l.setItemText(0, _translate("MainWindow", "Chó"))
        self.cb_l.setItemText(1, _translate("MainWindow", "Mèo"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Tiêm phòng"))
        self.label_7.setText(_translate("MainWindow", "Loại dịch vụ :"))
        self.checkBox_3.setText(_translate("MainWindow", "Phòng dại(2tr VND)"))
        self.checkBox_4.setText(_translate("MainWindow", "Phòng ký sinh(1,5tr VND)"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Dịch vụ spa"))
        self.label_2.setText(_translate("MainWindow", "Loại dịch vụ :"))
        self.checkBox.setText(_translate("MainWindow", "Tắm thơm(1tr VND)"))
        self.checkBox_2.setText(_translate("MainWindow", "Cắt tỉa lông(800K VND)"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Mã dịch vụ"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Tên khách hàng"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Số điện thoại"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Loại thú cưng"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Dịch vụ spa"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Tiêm phòng"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Thành tiền"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Ngày đăng ký"))
        self.bt_t.setText(_translate("MainWindow", "Thêm"))
        self.bt_t_2.setText(_translate("MainWindow", "Sửa "))
        self.bt_x.setText(_translate("MainWindow", "Xóa"))


    def them(self):
        tkh = self.tb_m.text()
        sdt = self.tb_t.text()
        loaitc = self.cb_l.currentText()
        thanhtien = 0
        if(self.checkBox.isChecked()):
            tt = "true"
            thanhtien = thanhtien + 1000000
        else:
            tt = "False"
        if(self.checkBox_2.isChecked()):
            ct = "true"
            thanhtien = thanhtien + 800000
        else:
            ct = "False"
        if(self.checkBox_3.isChecked()):
            pd = "true"
            thanhtien = thanhtien + 2000000
        else:
            pd = "False"
        if(self.checkBox_4.isChecked()):
            ks = "true"
            thanhtien = thanhtien + 1500000
        else:
            ks = "False"
        tc = dichvu("",tkh,sdt,loaitc,tt,ct,pd,ks,thanhtien)
        tc.them()
        self.hienthi()

    def sua(self):
        madv = self.madv
        tkh = self.tb_m.text()
        sdt = self.tb_t.text()
        loaitc = self.cb_l.currentText()
        thanhtien = 0
        if(self.checkBox.isChecked()):
            tt = "true"
            thanhtien = thanhtien + 1000000
        else:
            tt = "False"
        if(self.checkBox_2.isChecked()):
            ct = "true"
            thanhtien = thanhtien + 800000
        else:
            ct = "False"
        if(self.checkBox_3.isChecked()):
            pd = "true"
            thanhtien = thanhtien + 2000000
        else:
            pd = "False"
        if(self.checkBox_4.isChecked()):
            ks = "true"
            thanhtien = thanhtien + 1500000
        else:
            ks = "False"
        tc = dichvu(madv,tkh,sdt,loaitc,tt,ct,pd,ks,thanhtien)
        tc.sua()
        self.hienthi()

    def xoa(self):
        madv = self.madv
        dv = dichvu
        dv.xoa(madv)
        self.hienthi()

    def hienthi(self):      
        dv = dichvu
        data = dv.hienthi()
        self.nhaptable(data)
    
    def nhaptable(self,data):
        self.tableWidget.setRowCount(0)
        for row_data in data:
            row_position = self.tableWidget.rowCount()
            self.tableWidget.insertRow(row_position)
            for column_index, cell_data in enumerate(row_data):
                self.tableWidget.setItem(row_position, column_index, QTableWidgetItem(str(cell_data)))
    

    def cellclick(self):
        row = self.tableWidget.currentRow()
        self.madv = self.tableWidget.item(row,0).text()
        self.tb_m.setText(self.tableWidget.item(row,1).text())
        self.tb_t.setText(self.tableWidget.item(row,2).text())
        self.cb_l.setCurrentText(self.tableWidget.item(row,3).text())
        if(self.tableWidget.item(row,4).text() == "Trọn gói"):
            self.checkBox.setChecked(True)
            self.checkBox_2.setChecked(True)
        elif(self.tableWidget.item(row,4).text() == "Tắm thơm"):
            self.checkBox.setChecked(True)
        elif(self.tableWidget.item(row,4).text() == "Cắt tỉa lông"):
            self.checkBox_2.setChecked(True)
        if(self.tableWidget.item(row,5).text() == "Trọn gói"):
            self.checkBox_3.setChecked(True)
            self.checkBox_4.setChecked(True)
        elif(self.tableWidget.item(row,5).text() == "Phòng dại"):
            self.checkBox_3.setChecked(True)
        elif(self.tableWidget.item(row,5).text() == "Phòng ký sinh"):
            self.checkBox_4.setChecked(True)

import qldv_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindowdv()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
