# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tknc.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem
import os
import sys
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'SaveClass')))
from classtc import thucung

class Ui_MainWindowtknc(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1074, 653)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(390, 0, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(150, 50, 671, 16))
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 121, 111))
        self.pushButton.setStyleSheet("border-image: url(:/nc/Pet Haven.png);")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(150, 70, 811, 281))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 50, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(400, 100, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(410, 30, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.tb_tnc = QtWidgets.QLineEdit(self.groupBox)
        self.tb_tnc.setGeometry(QtCore.QRect(530, 100, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tb_tnc.setFont(font)
        self.tb_tnc.setObjectName("tb_tnc")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 120, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 190, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(400, 150, 381, 121))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(10, 40, 45, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.tb_tunc = QtWidgets.QLineEdit(self.groupBox_3)
        self.tb_tunc.setGeometry(QtCore.QRect(70, 30, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tb_tunc.setFont(font)
        self.tb_tunc.setObjectName("tb_tunc")
        self.tb_dnnc = QtWidgets.QLineEdit(self.groupBox_3)
        self.tb_dnnc.setGeometry(QtCore.QRect(70, 70, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tb_dnnc.setFont(font)
        self.tb_dnnc.setObjectName("tb_dnnc")
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(10, 80, 45, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.tb_gnc = QtWidgets.QLineEdit(self.groupBox)
        self.tb_gnc.setGeometry(QtCore.QRect(150, 120, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tb_gnc.setFont(font)
        self.tb_gnc.setObjectName("tb_gnc")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(150, 40, 54, 54))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.ck_m = QtWidgets.QCheckBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ck_m.setFont(font)
        self.ck_m.setObjectName("ck_m")
        self.gridLayout.addWidget(self.ck_m, 1, 0, 1, 1)
        self.ck_c = QtWidgets.QCheckBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ck_c.setFont(font)
        self.ck_c.setObjectName("ck_c")
        self.gridLayout.addWidget(self.ck_c, 0, 0, 1, 1)
        self.widget1 = QtWidgets.QWidget(self.groupBox)
        self.widget1.setGeometry(QtCore.QRect(530, 20, 130, 54))
        self.widget1.setObjectName("widget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ck_cai = QtWidgets.QCheckBox(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ck_cai.setFont(font)
        self.ck_cai.setObjectName("ck_cai")
        self.gridLayout_2.addWidget(self.ck_cai, 2, 0, 1, 1)
        self.ck_duc = QtWidgets.QCheckBox(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ck_duc.setFont(font)
        self.ck_duc.setObjectName("ck_duc")
        self.gridLayout_2.addWidget(self.ck_duc, 1, 0, 1, 1)
        self.widget2 = QtWidgets.QWidget(self.groupBox)
        self.widget2.setGeometry(QtCore.QRect(150, 180, 148, 54))
        self.widget2.setObjectName("widget2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ck_dtnc = QtWidgets.QCheckBox(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ck_dtnc.setFont(font)
        self.ck_dtnc.setObjectName("ck_dtnc")
        self.gridLayout_3.addWidget(self.ck_dtnc, 0, 0, 1, 1)
        self.ck_ctnc = QtWidgets.QCheckBox(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ck_ctnc.setFont(font)
        self.ck_ctnc.setObjectName("ck_ctnc")
        self.gridLayout_3.addWidget(self.ck_ctnc, 1, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(150, 360, 701, 231))
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.bt_tknc = QtWidgets.QPushButton(self.centralwidget)
        self.bt_tknc.setGeometry(QtCore.QRect(860, 360, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bt_tknc.setFont(font)
        self.bt_tknc.setObjectName("bt_tknc")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1074, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.bt_tknc.clicked.connect(lambda:self.tk())
        self.hienthi()


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Tìm kiếm nâng cao"))
        self.groupBox.setTitle(_translate("MainWindow", "Lọc"))
        self.label_4.setText(_translate("MainWindow", "Loại thú cưng:"))
        self.label_6.setText(_translate("MainWindow", "Tuổi thú cưng:"))
        self.label_7.setText(_translate("MainWindow", "Giới tính:"))
        self.label_5.setText(_translate("MainWindow", "Giống thú cưng:"))
        self.label_2.setText(_translate("MainWindow", "Tiêm phòng:"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Giá cả"))
        self.label_13.setText(_translate("MainWindow", "Từ :"))
        self.label_14.setText(_translate("MainWindow", "Đến :"))
        self.ck_m.setText(_translate("MainWindow", "Mèo"))
        self.ck_c.setText(_translate("MainWindow", "Chó"))
        self.ck_cai.setText(_translate("MainWindow", "Cái"))
        self.ck_duc.setText(_translate("MainWindow", "Đực"))
        self.ck_dtnc.setText(_translate("MainWindow", "Đã tiêm phòng"))
        self.ck_ctnc.setText(_translate("MainWindow", "Chưa tiêm phòng"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Mã thú cưng"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Loại thú cưng"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Giống thú cưng"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Tuổi thú cưng"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Giới tính"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Tiêm phòng"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Giá bán"))
        self.bt_tknc.setText(_translate("MainWindow", "Tìm kiếm"))
    def tk(self):
        giongnc = self.tb_gnc.text()
        tuoinc = self.tb_tnc.text()
        giatu = self.tb_tunc.text()
        giaden = self.tb_dnnc.text()
        if (self.ck_dtnc.isChecked() and  self.ck_ctnc.isChecked()):
            dtp = ""
        elif (self.ck_dtnc.isChecked()):
            dtp = "True"
        elif (self.ck_ctnc.isChecked()):
            dtp = "False"
        else:
            dtp = ""

        if (self.ck_c.isChecked() and  self.ck_m.isChecked()):
            loai = ""
        elif (self.ck_c.isChecked()):
            loai = "Chó"
        elif (self.ck_m.isChecked()):
            loai = "Mèo"
        else:
            loai = ""

        if (self.ck_duc.isChecked() and  self.ck_cai.isChecked()):
            gtnc = ""
        elif (self.ck_duc.isChecked()):
            gtnc = "Đực"
        elif (self.ck_cai.isChecked()):
            gtnc = "Cái"
        else:
            gtnc = ""
        tc = thucung
        data = tc.timkiemnc(loai,giongnc,tuoinc,dtp,gtnc,giatu,giaden)
        self.nhaptable(data)

    def hienthi(self):
        tc = thucung
        data = tc.hienthi()
        self.nhaptable(data)

    def nhaptable(self, data):
        self.tableWidget.setRowCount(0)
        for row_data in data:
            row_position = self.tableWidget.rowCount()
            self.tableWidget.insertRow(row_position)
            for column_index, cell_data in enumerate(row_data):
                self.tableWidget.setItem(row_position, column_index, QTableWidgetItem(str(cell_data)))

import TLNC


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindowtknc()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
